# Generated by Django 5.2.4 on 2025-10-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dodolist',
            name='title',
            field=models.CharField(default='Новая задача', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dodolist',
            name='image',
            field=models.ImageField(blank=True, upload_to='dodolist/images/'),
        ),
    ]
